### ISSUE TITLE
Configuration Issue with default-segment (default is not redirected)

### ISSUE THREAD

**Issue by meincms** [spoonerWeb/rlmp_language_detection#5]
Hi Champ

Thanks for your great updates on that extension. Well: I don't really get a solution for this issue:
- I am using rlmp_language_detection in combination with realurl.
- Here's my setup:

Language and contry definitions
L0 = de-ch (German Site for Switzerland, www.mysite.com/ch-de/start.html)
L1 = en (English Site for rest of the world , www.mysite.com/en/home.html)
L2 = de-de (German Site for Germany, www.mysite.com/de-de/start.html)

If i enforce TYPO3 to use the segment 

	config {
		defaultGetVars.L = 0
		...
		
a) If I don't use defaultGetVars.L = 0, the first call triggers the default segment without the lang-country-segment, like this: www.mysite.com/start.html, rlmp_language_detection ignores the segment and doesn't work hand in hand with realurl. no redirect for the language has been forced.

b) If I use the defaultGetVars.L = 0,  the lang-country-segment looks like this: www.mysite.com/de-ch/start.html, but rlmp_language_detection is not triggered anymore. the redirect in realurl is enforced, but the rlmp_language_detection won't do anything because it's not triggered. I am pretty sure the reason for not triggering the language is the following: [globalVar=GP:L=0,GP:L>0]...

The first call won't be redirected to the language segment. any idea what i do wrong? or is it possible the setup doesn't work in combination with the realurl setup the way i use it?

**Comment by meincms** [comment]
I was wondering how i can set the iso-code for the default language in typo3 on the root of the tree. do you think this might be a problem concerning the default setup of the typo3 site?

**Comment by spoonerWeb** [comment]
You have to install the extension "static_info_tables" to get the field for the iso code in the system language record.

**Comment by spoonerWeb** [comment]
Due to no feedback since 90 days I'll close this issue.
