### ISSUE TITLE
"rlmp_language_detection" not working.

### ISSUE THREAD

**Issue by typo3ua** [spoonerWeb/rlmp_language_detection#7]
TYPO3 6.2.12
rlmp_language_detection 7.0.0

and

TYPO3 6.2.12
rlmp_language_detection 3.0.1

My TS:
~~~
plugin.tx_rlmplanguagedetection_pi1 {
	defaultLang = de
	languageAliases >
	languageAliases {
		uk = en
		ua = en
		ru = en
	}
	countryCodeToLanguageCode >
	countryCodeToLanguageCode {
		uk = en
		ua = en
		ru = en
	}
}
page.987 =< plugin.tx_rlmplanguagedetection_pi1
~~~

not working. Why?

**Comment by spoonerWeb** [comment]
Looks good.
Did you include the static template?
Do you have an URL to test it?

**Comment by typo3ua** [comment]
I do it but not working.

**Comment by spoonerWeb** [comment]
Did you installed the extension "static_info_tables" and configured your system languages with the ISO codes?

**Comment by typo3ua** [comment]
Yes! Good work.
Thank you for your time.

**Comment by spoonerWeb** [comment]
You're welcome!

**Comment by typo3ua** [comment]
Hello, everybody!

I updated site and all extensions.

Now I have:
==
PHP version 5.3.28-pl3
TYPO3 CMS version 6.2.15
EXT: static_info_tables version 6.3.4
EXT: rlmp_language_detection version 7.0.3

Frontend:
==
~~~
Server error
500
~~~
Why?
I need ypur help.
