### ISSUE TITLE
not compatible with php < 5.4 (or not declared in ext_emconf.php)

### ISSUE THREAD

**Issue by jonnsn** [spoonerWeb/rlmp_language_detection#8]
Classes/LanguageDetection.php uses short array declaration [] instead of array() which is not compatible with php < 5.4. Yet the ext_emconf does not have dependency for php >= 5.4. So the extension leads to a fatal error when used with older versions of php.

Best Fix would imo be to avoid the use of short notation, but use array() instead (though even 5.4 has already reached End of Life).
The short notation is used in Lines 315 and 318.

**Comment by liayn** [comment]
This is fixed already in the 7.0.4 release. Please close.
