### ISSUE TITLE
ter Version 7.0.3 not compatible with TYPO3 6.2?

### ISSUE THREAD

**Issue by jonnsn** [spoonerWeb/rlmp_language_detection#9]
I have TYPO3 6.2.15, static_info_tables 6.3.4 and this extension in Version 7.0.3 from TER.
The extension queries sys_language for field "language_isocode". This column does not exist in my installation. After some research I found out, that the column does exist since TYPO3 7.1.

The option "useOldOneTreeConcept" does not use the field, but uses sys_language.title which is a value that can be defined as anything you want. In my case it does not fit the iso-code at least.
Also this option is there for TYPO3 prior to 3.6.0 if I understand the comment the right way, so I wouldn't have to use it with 6.2.

Am I missing something?

**Comment by typo3ua** [comment]
I've got error also... #7

**Comment by jonnsn** [comment]
I installed version 2.3.1 then, which seems to work well with 6.2.

**Comment by typo3ua** [comment]
I install new version EXT: rlmp_language_detection version 7.0.4 
Message about "Server error 500" disappeared but the "rlmp_language_detection" does not work.

**Comment by liayn** [comment]
This is fixed with 301dc53a80354019a6eb099c24e4e52c0bfb7966 now
